#!/usr/bin/env python3
"""Build a standalone index.html from Main.dc.html.

Main.dc.html is the Design canvas source and only runs inside the canvas editor.
This script wraps the same markup and logic with a small React-based runtime so
the prototype opens as an ordinary web page (for example on GitHub Pages).

Usage: python3 build.py   (run from this folder; rewrites index.html)
"""
import pathlib
import re

here = pathlib.Path(__file__).parent
src = (here / "Main.dc.html").read_text(encoding="utf-8")

helmet = re.search(r"<helmet>(.*?)</helmet>", src, re.S).group(1).strip()
markup = re.search(r"</helmet>(.*?)</x-dc>", src, re.S).group(1).strip()
logic = re.search(r'<script type="text/x-dc"[^>]*>(.*?)</script>', src, re.S).group(1).strip()
title = re.search(r"<title>(.*?)</title>", src, re.S).group(1).strip()

RUNTIME = r"""
(function () {
  var h = React.createElement;
  var ATTR = { 'class': 'className', 'for': 'htmlFor', onclick: 'onClick', onchange: 'onChange' };
  var WHOLE = /^\s*\{\{([^}]+)\}\}\s*$/;

  function look(path, scope) {
    path = path.trim();
    if (path === 'true') return true;
    if (path === 'false') return false;
    var parts = path.split('.');
    var v, found = false;
    for (var i = scope.length - 1; i >= 0; i--) {
      if (parts[0] in scope[i]) { v = scope[i][parts[0]]; found = true; break; }
    }
    if (!found) return undefined;
    for (var k = 1; k < parts.length && v != null; k++) v = v[parts[k]];
    return v;
  }
  function val(str, scope) {
    var m = str.match(WHOLE);
    if (m) return look(m[1], scope);
    return str.replace(/\{\{([^}]+)\}\}/g, function (_, p) {
      var v = look(p, scope);
      return v == null ? '' : String(v);
    });
  }
  function styleObj(str) {
    var o = {};
    str.split(';').forEach(function (d) {
      var i = d.indexOf(':');
      if (i < 0) return;
      var k = d.slice(0, i).trim();
      if (!k) return;
      o[k.replace(/-([a-z])/g, function (_, c) { return c.toUpperCase(); })] = d.slice(i + 1).trim();
    });
    return o;
  }
  function kids(node, scope) {
    var out = [];
    node.childNodes.forEach(function (c, i) {
      var r = conv(c, scope, i);
      if (r != null && r !== false) out.push(r);
    });
    return out;
  }
  function conv(node, scope, key) {
    if (node.nodeType === 3) {
      var t = node.nodeValue.replace(/\s+/g, ' ').trim();
      if (!t) return null;
      var tv = val(t, scope);
      return tv == null ? null : String(tv);
    }
    if (node.nodeType !== 1) return null;
    var tag = node.localName;
    if (tag === 'sc-if') {
      if (!val(node.getAttribute('value') || '', scope)) return null;
      return h.apply(null, [React.Fragment, { key: key }].concat(kids(node, scope)));
    }
    if (tag === 'sc-for') {
      var list = val(node.getAttribute('list') || '', scope) || [];
      var as = node.getAttribute('as') || 'item';
      return h.apply(null, [React.Fragment, { key: key }].concat(list.map(function (item, i) {
        var frame = { $index: i };
        frame[as] = item;
        return h.apply(null, [React.Fragment, { key: i }].concat(kids(node, scope.concat([frame]))));
      })));
    }
    var props = { key: key };
    Array.prototype.forEach.call(node.attributes, function (a) {
      var name = a.name;
      if (name.indexOf('hint-') === 0) return;
      var v = val(a.value, scope);
      if (name === 'style') v = styleObj(String(v));
      else if (name.indexOf('aria-') === 0) v = String(v);
      else if (name === 'value' && v == null) v = '';
      props[ATTR[name] || name] = v;
    });
    return h.apply(null, [tag, props].concat(kids(node, scope)));
  }

  window.DCLogic = class extends React.Component {
    render() {
      var tpl = document.getElementById('dc-template');
      return h.apply(null, [React.Fragment, null].concat(kids(tpl.content, [this.renderVals()])));
    }
  };
})();
"""

page = f"""<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<!-- Generated by build.py from Main.dc.html. Edit the source, then rebuild. -->
{helmet}
</head>
<body>
<div id="root"></div>
<template id="dc-template">
{markup}
</template>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/18.3.1/umd/react.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.3.1/umd/react-dom.production.min.js"></script>
<script>{RUNTIME}</script>
<script>
{logic}
ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(Component));
</script>
</body>
</html>
"""

(here / "index.html").write_text(page, encoding="utf-8")
print("Wrote", here / "index.html", len(page), "bytes")
